services:
  bookify-webapi:
    image: ${DOCKER_REGISTRY-}bookifywebapi
    container_name: Bookify.WebApi
    build:
      context: .
      dockerfile: Bookify.WebApi/Dockerfile
    depends_on:
      - bookify-db
  bookify-db:
    image: postgres:latest
    container_name: Bookify.Db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bookifydb
    volumes:
      -  ./.containers/database:/var/lib/postgresql
    ports:
      - 5432:5432
  bookify-idp:
    image: quay.io/keycloak/keycloak:23.0.0
    container_name: Bookify.Identity
    command: start-dev --import-realm
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
      - ./.containers/identity:/opt/keycloak/data
      - ./.files/bookify-realm-export.json:/opt/keycloak/data/import/realm.json   
    ports:
      - 18080:8080
